[package]
name = "i2c-rs"
version = "0.2.0"
authors = ["Ryan Plauche <ryan@kubos.co>", "Patrick Oppel <patrick.oppel94@gmail.com>"]
edition = "2018"

[dependencies]
i2c-linux = "0.1"
hal-stream = { git = "ssh://git@github.com/Cube-OS/hal-stream"}
