name: Release

on:
  push:
    tags:
      - 'v*' # Trigger workflow on push to tags that start with 'v'
    # branches:
    #   - main # Trigger workflow on push to the main branch

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    # Run ktra action
    - name: Run ktra
      uses: patrickoppel/ktra/.github/actions@develop
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}