name: Release

on:
  push:
    branches:
      - main # Trigger workflow on push to the main branch

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: stable

    # Checkout Code
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: ${{ github.event.repository.name }}

    # Run ktra action
    - name: Run ktra
      uses: patrickoppel/ktra/.github/actions/action.yml@main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}